project:
  type: website
  output-dir: docs

website:
  title: "WHO Mpox Clinical Data Platform"
  navbar:
    left:
      - href: mpox_who_dashboard.qmd
        text: " "

format:
  html:
    theme: [flatly,theme/custom2.css]
    css: theme/custom2.css
    toc: true

